kind: pipeline
type: docker
name: 发布


clone:
  disable: true


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: gopath
        path: /var/lib/gopath
      - name: gocache
        path: /var/lib/gocache
      - name: linter
        path: /var/lib/linter
    settings:
      output:
        name: plugin

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_tencentyun_ccr
    settings:
      repository: dronestock/todo
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
  - name: gopath
    host:
      path: /var/lib/cache/gopath
  - name: gocache
    host:
      path: /var/lib/cache/gocache
  - name: linter
    host:
      path: /var/lib/cache/linter
